app/main.py
#!/usr/bin/python3
__author__ = "u/wontfixit"
__copyright__ = "Copyright 2020"
__license__ = "GPL"
__version__ = "1.0.0"

import time
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from DBhelper import *
from datetime import datetime
import configparser
import logging as log

#TODO read artist which are flagged from "play less" function

now = datetime.now()
timestamp = datetime.timestamp(now)
timeMinusOneDay = timestamp - (24 * 60 * 60)

LOG_FILENAME = "../log_main.log"

___debug___ = True
___runprod___ = True

if ___debug___ == True:
    log.basicConfig(handlers=[
        log.FileHandler(LOG_FILENAME),
        log.StreamHandler()], level=log.INFO, format='%(asctime)s ; %(levelname)s ; %(funcName)s() ; %(message)s')


class skipr:
    def __init__(self):
        config = configparser.ConfigParser()
        config.read('../config.ini')

        self.client_id = config['DEFAULT']['client_id']
        self.client_secret = config['DEFAULT']['client_secret']

        print(self.client_id)
        print(self.client_secret)

        self.user = None
        self.id_user = None
        self.name_user = None
        self.name_track = None
        self.id_artist = None
        self.name_artist = None
        self.id_user = None
        self.id_track = None
        self.db = None

        scope = "user-read-currently-playing user-read-playback-state user-modify-playback-state"
        self.sp = spotipy.Spotify(auth_manager=SpotifyOAuth(scope=scope, client_id=self.client_id,
                                                            client_secret=self.client_secret,
                                                            redirect_uri='http://127.0.0.1:8080/callback'))
                                                            #redirect_uri='https://example.com'))


    def getDatabase(self, db):
        # get Database obj and pass it
        self.db = db
        return db

    def addNewIgnore(self,arg_name_artist):
        # add the current artist to ignore
        # user input must be done as well
        self.getCurrentUserData()
       # self.getDatabase(self.db.addNewIgnore(self.id_user, self.name_user, None, arg_name_artist))

        print(self.sp.search(q=arg_name_artist, limit=10, type="artist"))


    def updateIgnore(self):
        # remove artist from ignore list
        None

    def getIgnoredArtistsByUser(self):
        return self.getDatabase(self.db.getArtistByUser(self.id_user, self.id_artist, self.name_artist))

    def getCurrentPlayingTrack(self):
        res = self.sp.current_user_playing_track()
        log.info("{}".format(res))
        if res is not None:
            self.name_track = res["item"]["name"]
            self.id_track = res["item"]["id"]
            artists = res["item"]["artists"]

            for artist in artists:
                self.name_artist = artist["name"]
                self.id_artist = artist["id"]
                if self.getIgnoredArtistsByUser() is True:
                    self.nextTrack()
        else:
            log.info("No running Track for {}".format(self.user["display_name"]))
        return self.name_artist,self.name_track

    def getCurrentUserData(self):
        self.user = self.sp.current_user()
        self.id_user = self.user["id"]
        self.name_user = self.user["display_name"]

    def nextTrack(self):
        self.sp.next_track(device_id=None)
        log.info("Track skipped User: {} - Artist: {}".format(self.user["display_name"], self.name_artist))



##############################################################################################################
if __name__ == "__main__":

    while True:
        try:
            skiprobj = skipr()
            db = DBhelper()
            skiprobj.getDatabase(db)
            skiprobj.getCurrentUserData()
            skiprobj.getCurrentPlayingTrack()
            time.sleep(5)
        except Exception as err:
            log.error("{}".format(err))

app/routes/routes.py
import os
from flask import render_template, Blueprint, request, redirect, url_for, session

import spotipy
from spotipy.oauth2 import SpotifyOAuth
from app.routes.Spotify_Config_Helper import Spotify_Config_Helper,skipr
import uuid
from DBhelper import *


spothelp = Spotify_Config_Helper()

SPOTIPY_CLIENT_ID = spothelp.SPOTIPY_CLIENT_ID
SPOTIPY_CLIENT_SECRET = spothelp.SPOTIPY_CLIENT_SECRET
SPOTIPY_REDIRECT_URI = spothelp.SPOTIPY_REDIRECT_URI

os.environ['SPOTIPY_CLIENT_ID'] = SPOTIPY_CLIENT_ID
os.environ['SPOTIPY_CLIENT_SECRET'] = SPOTIPY_CLIENT_SECRET
os.environ['SPOTIPY_REDIRECT_URI'] = SPOTIPY_REDIRECT_URI


caches_folder = './.spotify_caches/'
if not os.path.exists(caches_folder):
    os.makedirs(caches_folder)

def session_cache_path():
    session_tmp = caches_folder + session.get('uuid')
    print(str(session_tmp))
    return session_tmp

blueprint = Blueprint('app', __name__)


@blueprint.route("/login", methods=['POST', 'GET'])
def login():
    if not session.get('uuid'):
        # Step 1. Visitor is unknown, give random ID
        session['uuid'] = str(uuid.uuid4())

    scope = "user-read-currently-playing user-read-playback-state user-modify-playback-state"
    auth_manager = spotipy.oauth2.SpotifyOAuth(scope=scope, cache_path=session_cache_path(),show_dialog=True)

    return redirect(auth_manager.get_authorize_url())


@blueprint.route("/callback")
def callback():
    # Requests refresh and access tokens
    auth_token = request.args.get('code')

    auth_manager = spotipy.oauth2.SpotifyOAuth(cache_path=session_cache_path()
                                               ,client_id=SPOTIPY_CLIENT_ID,
                                                          client_secret=SPOTIPY_CLIENT_SECRET,
                                                        redirect_uri=SPOTIPY_REDIRECT_URI)

    spotify = spotipy.Spotify(auth_manager=auth_manager)
    skiprobj = skipr(spotify)
    db = DBhelper()
    skiprobj.getDatabase(db)
    skiprobj.addNewUserToken("a","b","c")

    if request.args.get("code"):

    #   Step 3. Being redirected from Spotify auth page
        auth_manager.get_access_token(request.args.get("code"))
        return redirect('/me')

    if not auth_manager.get_cached_token():
        print("NO Cached TOKEN")
     # Step 2. Display sign in link when no token
        auth_url = auth_manager.get_authorize_url()
        return redirect(auth_manager.get_authorize_url())


    return redirect(url_for("app.me"))


@blueprint.route("/me")
def me():
    auth_manager = spotipy.oauth2.SpotifyOAuth(cache_path=session_cache_path())
    spotify = spotipy.Spotify(auth_manager=auth_manager)
    spotify = spotipy.Spotify(auth_manager=auth_manager)
    skiprobj = skipr(spotify)
    db = DBhelper()
    skiprobj.getDatabase(db)

    skiprobj.getCurrentUserData()
    skiprobj.getCurrentPlayingTrack()
    var = skiprobj.name_user
    tr = skiprobj.name_track
    at = skiprobj.name_artist
    print(at)
    return render_template("me.html",name_of_me=var,track_playing=tr,user_pp_url=skiprobj.user_pp_url)

@blueprint.route("/")
def main():
    return render_template('main.html')

@blueprint.route("/not-found")
def not_found():
    return render_template('404.html')


@blueprint.route("/load", methods=['GET', 'POST'])
def load():
    authorization_header = session['authorization_header']
    extract_letters = lambda x: ''.join([letter for letter in x if not letter.isdigit()])

    if request.method == 'GET':
        # -------- Get user's name, id, and set session --------
        profile_data = spotify_handler.get_user_profile_data(authorization_header)
        user_display_name, user_id = profile_data['display_name'], profile_data['id']
        session['user_id'], session['user_display_name'] = user_id, user_display_name

        # -------- Get user playlist data --------
        playlist_data = spotify_handler.get_user_playlist_data(authorization_header, user_id)

        return render_template('select.html',
                               user_display_name=user_display_name,
                               playlists_data=playlist_data,
                               func=extract_letters)

    return render_template('404.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="eng">

    <head>
        <meta charset="utf-8">
        <title>Spotify Skipr - next your unwanted Artists</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Signika">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
              integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
              crossorigin="anonymous">

        <script src="https://code.jquery.com/jquery-3.5.1.js"></script>

        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/untitled-1.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/untitled.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-slider.css') }}">

    </head>

    <body>
        <h1>Spotify next this shit</h1>

        {% block content %}
        {% endblock %}

        {#        <p class="text-center d-xl-flex align-items-xl-start" id="made-by">Made by <a#}
        {#                href="https://reddit.com/u/wontfixit">u/wontfixit</a>.</p>#}

        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
                integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
                integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
                crossorigin="anonymous"></script>

        <script src="../static/js/main.js"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
        <script src="../static/js/bootstrap-slider.js"></script>


    </body>

</html>

app/templates/main.html
{% extends "base.html" %}
{% block content %}


    <body>
        <div class="container text-center hi">
            <p class="main-p">
                Autoskip you most hated artist<br>
            </p>
        </div>

        <div class="text-center" style="padding-top: 47px;">
            <a href="{{ url_for('app.login') }}">
                <button class="btn btn-primary" id="login-btn" type="button">
                    Log in with Spotify
                </button>
            </a>

        </div>
        <p class="greyed">
            *We are using Spotify's secure login to connect to your account.<br>
            We store your username, userid, artistname and artistid in our DB - not more
        </p>


    </body>

{% endblock %}

app/templates/me.html
{% extends "base.html" %}
{% block content %}


    <body>
    Name: {{name_of_me}}<br>
    Track: {{track_playing}} <br>
    <img src="{{user_pp_url}}">


    </body>

{% endblock %}

app/templates/page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ mytitle }}</title>
</head>
<body>
{{ mytitle }}
<form class="form"  method="POST" action="#">
            <label name="artistname">Artist</label>
            <input type="text" class="form-control" autofocus="autofocus" id="answer" name="answer">
            <button name="send" action="send">ignorieren</button>
        </form>
</body>
</html>